### MLBook-1
#### Exercise 4
以IRIS数据集前100个样本为例

* 4.1
实现“自助法”过程，打印出最终选取的“测试集/验证集”和“训练集”的index

In [192]:
from sklearn.datasets import load_iris
import numpy as np


def bootstrap(length):
    """
    Return:
        indexes of train/target datasets.
    """
    train = set()
    for m in range(length):
        train.add(np.random.randint(0, length))
    test = set(range(length)) - train
    return list(train), list(test)

iris = load_iris()
data_x = iris.data[:100]
data_y = iris.target[:100]

idx_train, idx_test = bootstrap(len(data_x))
print("Train: ", idx_train)
print("Test : ", idx_test)

train_x = data_x[idx_train]
train_y = data_y[idx_train]
test_x = data_x[idx_test]
test_y = data_y[idx_test]

Train:  [0, 1, 3, 4, 5, 6, 10, 12, 14, 15, 16, 19, 20, 21, 22, 24, 25, 26, 27, 29, 31, 33, 35, 40, 42, 43, 48, 49, 51, 53, 55, 56, 60, 61, 62, 65, 66, 67, 69, 71, 72, 73, 74, 75, 76, 81, 82, 83, 84, 86, 87, 88, 89, 90, 91, 96, 98, 99]
Test :  [2, 7, 8, 9, 11, 13, 17, 18, 23, 28, 30, 32, 34, 36, 37, 38, 39, 41, 44, 45, 46, 47, 50, 52, 54, 57, 58, 59, 63, 64, 68, 70, 77, 78, 79, 80, 85, 92, 93, 94, 95, 97]


---
* 4.2
用model = linear_model.SGDClassifier()对上面选取的“训练集”进行训练，计算“测试集/验证集”和“训练集”上的正确率、混淆矩阵、P、R、F1
* 4.3
用model = svm.SVC(gamma=0.001, C=100) 对上面选取的“训练集”进行训练，计算“测试集/验证集”和“训练集”上的正确率、混淆矩阵、P、R、F1
* 4.4
用model=linear_model.LogisticRegression()对上面选取的“训练集”进行训练，可以得到predict_proba_y = model.predict_proba(train_x)[:,1]。计算“测试集/验证集”和“训练集”的AUC值，画出ROC曲线。
* 4.5
用model = svm.SVC(gamma=0.001, C=100)，计算“测试集/验证集”和“训练集”的AUC值，画出ROC曲线。

In [193]:
from sklearn import linear_model
from sklearn import metrics
from sklearn import svm


def score(model, tr_x, tr_y, test_x, test_y):
    model.fit(tr_x, tr_y)
    y_pred = model.predict(test_x)
    y_true = test_y
    accuracy = metrics.accuracy_score(y_true, y_pred)
    cm = metrics.confusion_matrix(y_true, y_pred)
    P = metrics.precision_score(y_true, y_pred)
    R = metrics.recall_score(y_true, y_pred)
    F1 = metrics.f1_score(y_true, y_pred)
    print("Confusion Matrix: \n", cm)
    print("Accuracy: %.2f" % accuracy)
    print("Precision: %.2f" % P)
    print("Recall: %.2f" % R)
    print("F1: %.2f\n" % F1)

print("*" * 5 + " 4.2 Score of SDGClassifier " + "*" * 5)
score(linear_model.SGDClassifier(), train_x, train_y, test_x, test_y)
print("*" * 5 + " 4.3 Score of SVC " + "*" * 5)
score(svm.SVC(), train_x, train_y, test_x, test_y)
print("*" * 5 + " 4.4 Score of LogisticRegression " + "*" * 5)
score(linear_model.LogisticRegression(), train_x, train_y, test_x, test_y)
print("*" * 5 + " 4.5 Score of SVC(gamma=0.001, C=100) " + "*" * 5)
score(svm.SVC(gamma=0.001, C=100), train_x, train_y, test_x, test_y)

***** 4.2 Score of SDGClassifier *****
Confusion Matrix: 
 [[22  0]
 [ 0 20]]
Accuracy: 1.00
Precision: 1.00
Recall: 1.00
F1: 1.00

***** 4.3 Score of SVC *****
Confusion Matrix: 
 [[22  0]
 [ 0 20]]
Accuracy: 1.00
Precision: 1.00
Recall: 1.00
F1: 1.00

***** 4.4 Score of LogisticRegression *****
Confusion Matrix: 
 [[22  0]
 [ 0 20]]
Accuracy: 1.00
Precision: 1.00
Recall: 1.00
F1: 1.00

***** 4.5 Score of SVC(gamma=0.001, C=100) *****
Confusion Matrix: 
 [[22  0]
 [ 0 20]]
Accuracy: 1.00
Precision: 1.00
Recall: 1.00
F1: 1.00



In [ ]:
print("Draw 4.4&4.5 ROC curve.")